# freexlib.com portal
root /var/www/freexlib-portal;
index index.html;

gzip on;
gzip_min_length 1024;
gzip_types text/css text/javascript application/javascript;

location / {
    try_files $uri $uri/ /index.html;
}

location = /index.html {
    add_header Cache-Control "no-cache";
}
